---
title: "Global surface temperatures"
author: "Braden Buchanan"
date: "2023-12-17"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load libraries
```{r}
library(tidyverse)
library(psych)
library(reshape2)
```


# Load Data
```{r}
tuesdata <- tidytuesdayR::tt_load('2023-07-11')
tuesdata <- tidytuesdayR::tt_load(2023, week = 28)

global_temps <- tuesdata$global_temps
nh_temps <- tuesdata$nh_temps
sh_temps <- tuesdata$sh_temps
zonann_temps <- tuesdata$zonann_temps
```


```{r}
summary(global_temps)
describe(global_temps)
```

# Global Weather change in June over time
```{r}
global_temps %>%
  select(Year, Jun) %>%
  ggplot(aes(Year, Jun)) +
  geom_line() + 
  labs(title = "Global Weather change over time for June")
```

# What is the average weather change over year? 
```{r}
global_temps %>%
  select(Year, `J-D`) %>%
  ggplot(aes(Year, `J-D`)) + 
  geom_line() +
  labs(title = "Global Weather change over time")
```

# Monthly Temperature Anomalies Over Years
```{r}
# Reshape data to long format
global_data_long <- melt(global_temps, id.vars = "Year", variable.name = "Month", value.name = "Temp")

# Convert Month to a factor to ensure proper ordering in the plot
global_data_long$Month <- factor(global_data_long$Month, levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))

# Plot
ggplot(global_data_long, aes(x = Year, y = Temp)) +
  geom_line(aes(color = Month)) +
  facet_wrap(~ Month, scales = "free_y") +
  theme_minimal() +
  labs(title = "Monthly Temperature Anomalies Over Years",
       x = "Year",
       y = "Temperature Anomaly") +
  theme(legend.position = "bottom")
```

