---
title: "coffeeRatings"
author: "Braden Buchanan"
date: "2023-09-13"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

For this tidyTuesday, I'm following along David Robinson's video on YouTube going through this dataset. 

https://www.youtube.com/watch?v=-1x8Kpyndss&t=2694s

# Import Data
```{r}
coffee_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv') %>%
  mutate(coffee_id = row_number()) %>%
  filter(total_cup_points > 0)
```

# Load packages
```{r}
library(tidyverse)
library(stringr)
library(scales)
install.packages("jsonlite")
library(jsonlite)
theme_set(theme_light())
```

```{r}
coffee_ratings %>%
  count(species, sort = TRUE)

coffee_lumped <- coffee_ratings %>%
  filter(!is.na(variety),
         total_cup_points > 10) %>%
  mutate(variety = fct_lump(variety, 10), sort = TRUE)
  
coffee_lumped %>%
  ggplot(aes(total_cup_points, variety)) + 
  geom_boxplot()

coffee_lumped %>%
  ggplot(aes(total_cup_points, fill = variety)) + 
  geom_histogram(binwidth = 2) +
  facet_wrap(~variety, scale = "free_y") +
  theme(legend.position = "none")
  

coffee_ratings %>%
  mutate(coffee_id = row_number()) %>%
  select(coffee_id, total_cup_points, species, variety, owner, farm_name, country_of_origin, aroma:moisture)
```

```{r}
#trick to see which columns have missing NA values 
coffee_ratings %>%
  summarise(across(everything(), ~ mean(!is.na(.)))) %>%
  gather() %>%
  view()

coffee_ratings %>%
  count(producer, sort = TRUE)

coffee_ratings %>%
  count(company, sort = TRUE)

coffee_ratings %>%
  count(color, sort = TRUE)

coffee_ratings %>%
  count(country = fct_lump(country_of_origin, 12), sort = TRUE) %>%
  filter(!is.na(country)) %>%
  mutate(country = fct_reorder(country, n)) %>%
  ggplot(aes(n, country)) +
  geom_col()
  
coffee_ratings %>%
  mutate(country = fct_lump(country_of_origin, 12),
         country = fct_reorder(country, total_cup_points)) %>%
  ggplot(aes(total_cup_points, country)) + 
  geom_boxplot()
```

