---
title: 'Dplyr Advanced Guide: data cleaning, reshaping, and merging with lubridate,
  stringr, tidyr, ggplot2'
author: "Braden Buchanan"
date: "2024-01-01"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
music_df <- billboard100 %>%
  select(date:artist, weeks_popular = 'weeks.on.board')

music_df
```

```{r}
library(lubridate)
library(stringr)
```

```{r}
music_df %>%
  mutate(date = mdy(date)) %>%
  select(date) %>%
  head(5)
```

```{r}
music_df.cleaned = 
  music_df %>%
  mutate(date = mdy(date),
         primary_artist = ifelse(str_detect(artist, 'Featuring'),
                                 str_match(artist, '(.*)\\sFeaturing')[,2],
                                 artist),
         featured_artist = str_match(artist, 'Featuring\\s(.*)')[,2])
```

```{r}
library(tidyr)
```

```{r}
music_df.cleaned %>%
  distinct(song, primary_artist, featured_artist) %>%
  pivot_longer(2:3, names_to = 'artist_type', values_to = 'artist_name')
```

